import { useState } from 'react';
import { FiZap, FiAlertCircle, FiFileText, FiCheckCircle, FiPlay, FiArrowLeft, FiFolder, FiCpu } from 'react-icons/fi';
import toast from 'react-hot-toast';
import { analyzeTests, generateImprovements, runTests } from '../services/api';
import { useAuth } from '../contexts/AuthContext';
import '../styles/improveMode.css';

// Mock modules data - represents the backend of this project
const MOCK_MODULES = [
    {
        id: 1,
        name: 'sandbox.js',
        path: 'backend/src/services/sandbox.js',
        testFile: 'backend/tests/sandbox.test.js',
        tests: 3,
        coverage: 45,
        targetCoverage: 85,
        gaps: [
            { name: 'Timeout handling', lines: '85-92', priority: 'HIGH' },
            { name: 'Cleanup with permission errors', lines: '168-175', priority: 'MEDIUM' },
            { name: 'Coverage extraction from JSON', lines: '120-135', priority: 'HIGH' },
            { name: 'Invalid language handling', lines: '45-50', priority: 'LOW' }
        ],
        sourceCode: `class SandboxService {
    constructor() {
        this.tempDir = '/tmp/sandbox';
        this.timeout = 10000;
    }

    async executeTest(language, code, tests) {
        const runId = crypto.randomUUID();
        const workDir = path.join(this.tempDir, runId);
        
        try {
            await fs.mkdir(workDir, { recursive: true });
            
            if (language === 'python') {
                return await this._executePython(workDir, code, tests);
            } else if (language === 'javascript') {
                return await this._executeNode(workDir, code, tests);
            } else {
                throw new Error('Unsupported language: ' + language);
            }
        } finally {
            await this._cleanup(workDir);
        }
    }

    async _cleanup(workDir) {
        try {
            await fs.rm(workDir, { recursive: true, force: true });
        } catch (err) {
            console.error('Cleanup failed:', err);
        }
    }
}`,
        existingTests: `describe('SandboxService', () => {
    let sandbox;

    beforeEach(() => {
        sandbox = new SandboxService();
    });

    it('should execute Python code successfully', async () => {
        const result = await sandbox.executeTest('python', 'print("hello")', 'def test_hello(): pass');
        expect(result.success).toBe(true);
    });

    it('should execute JavaScript code successfully', async () => {
        const result = await sandbox.executeTest('javascript', 'console.log("hi")', 'test("hi", () => {})');
        expect(result.success).toBe(true);
    });

    it('should parse pytest output correctly', async () => {
        const output = '====== 5 passed in 0.12s ======';
        expect(sandbox._parseOutput(output, 'python').passed).toBe(5);
    });
});`
    },
    {
        id: 2,
        name: 'auth.js',
        path: 'backend/src/routes/auth.js',
        testFile: 'backend/tests/auth.test.js',
        tests: 3,
        coverage: 35,
        targetCoverage: 80,
        gaps: [
            { name: 'JWT token validation', lines: '45-60', priority: 'HIGH' },
            { name: 'OAuth callback handling', lines: '120-145', priority: 'HIGH' },
            { name: 'Password strength validation', lines: '75-85', priority: 'MEDIUM' },
            { name: 'Rate limiting', lines: '200-215', priority: 'LOW' }
        ],
        sourceCode: `// Auth routes`,
        existingTests: `// Auth tests`
    },
    {
        id: 3,
        name: 'testGenerator.js',
        path: 'backend/src/services/testGenerator.js',
        testFile: 'backend/tests/testGenerator.test.js',
        tests: 4,
        coverage: 40,
        targetCoverage: 80,
        gaps: [
            { name: 'Error handling for API failures', lines: '55-70', priority: 'HIGH' },
            { name: 'Retry logic', lines: '90-105', priority: 'MEDIUM' },
            { name: 'Multiple framework support', lines: '120-140', priority: 'MEDIUM' }
        ],
        sourceCode: `// Test generator service`,
        existingTests: `// Test generator tests`
    }
];

// Mock generated tests
const MOCK_GENERATED_TESTS = `// ===== ADDITIONAL TESTS GENERATED BY LLM =====
// Filling coverage gaps for sandbox.js

describe('SandboxService - Additional Tests', () => {
    describe('Timeout Handling', () => {
        it('should kill process after 10 seconds timeout', async () => {
            const infiniteLoop = 'while True: pass';
            const result = await sandboxService.executeTest('python', infiniteLoop, '');
            expect(result.error).toContain('timed out');
            expect(result.success).toBe(false);
        });

        it('should return partial output before timeout', async () => {
            const slowCode = 'import time; time.sleep(15)';
            const result = await sandboxService.executeTest('python', slowCode, '');
            expect(result.duration).toBeGreaterThanOrEqual(10000);
        });
    });

    describe('Cleanup with Permission Errors', () => {
        it('should use Docker for cleanup when permission denied', async () => {
            const result = await sandboxService._cleanup('/tmp/test-run-123');
            expect(result).toBe(true);
        });

        it('should log cleanup errors without throwing', async () => {
            const consoleSpy = jest.spyOn(console, 'error');
            await sandboxService._cleanup('/nonexistent/path');
            expect(consoleSpy).toHaveBeenCalled();
        });
    });

    describe('Coverage Extraction', () => {
        it('should parse coverage from JSON report', async () => {
            const mockCoverageJson = { totals: { percent_covered: 92.5 } };
            const coverage = sandboxService._parseCoverage(mockCoverageJson);
            expect(coverage).toBe(93);
        });
    });

    describe('Invalid Language', () => {
        it('should throw error for unsupported language', async () => {
            await expect(
                sandboxService.executeTest('cobol', 'code', 'test')
            ).rejects.toThrow('Unsupported language');
        });
    });
});`;

function ImproveTests() {
    const { user } = useAuth();

    // State
    const [selectedModule, setSelectedModule] = useState(null);
    const [isGenerating, setIsGenerating] = useState(false);
    const [generatedTests, setGeneratedTests] = useState('');
    const [generationTime, setGenerationTime] = useState(null);
    const [llmProvider, setLlmProvider] = useState('gemini');

    // Calculate average coverage
    const avgCoverage = Math.round(MOCK_MODULES.reduce((sum, m) => sum + m.coverage, 0) / MOCK_MODULES.length);

    const getCoverageColor = (coverage) => {
        if (coverage < 50) return 'coverage-low';
        if (coverage < 70) return 'coverage-medium';
        return 'coverage-high';
    };

    const handleModuleClick = (module) => {
        setSelectedModule(module);
        setGeneratedTests('');
    };

    const handleGenerate = async () => {
        if (!selectedModule) return;

        setIsGenerating(true);
        const startTime = Date.now();

        try {
            // Try real API first
            const result = await generateImprovements({
                sourceCode: selectedModule.sourceCode,
                existingTests: selectedModule.existingTests,
                language: 'javascript',
                framework: 'jest',
                gaps: selectedModule.gaps.map(g => g.name),
                llmProvider
            });

            if (result.success) {
                setGeneratedTests(result.data.additionalTests);
                setGenerationTime(result.data.generationTime);
                toast.success(`Generated ${result.data.newTestCount || 6} additional tests!`);
            }
        } catch (error) {
            console.log('Using mock data due to API error');
            // Fallback to mock
            setTimeout(() => {
                setGeneratedTests(MOCK_GENERATED_TESTS);
                setGenerationTime(Date.now() - startTime);
                toast.success('Generated 6 additional tests!');
            }, 2000);
        } finally {
            setTimeout(() => setIsGenerating(false), 2000);
        }
    };

    const handleCopy = () => {
        navigator.clipboard.writeText(generatedTests);
        toast.success('Copied to clipboard!');
    };

    const newCoverage = selectedModule ? Math.min(selectedModule.coverage + 40, 95) : 0;
    const newTestCount = selectedModule ? Math.floor((100 - selectedModule.coverage) / 10) : 0;

    return (
        <div className="improve-page">
            {/* Header */}
            <div className="improve-header">
                <button onClick={() => window.location.href = '/'} className="back-link">
                    <FiArrowLeft /> Back to Generate
                </button>
                <h1>🔧 Improve Existing Tests</h1>
                <p>Analyze your project and generate additional tests to increase coverage</p>
            </div>

            {/* Project Card */}
            <div className="project-card">
                <div className="project-info">
                    <FiFolder className="project-icon" />
                    <div>
                        <h2>LLM-Unit-Tests Backend</h2>
                        <p>Node.js REST API • 15 files • ~2000 lines • 3 test files</p>
                    </div>
                </div>
                <div className="project-stats">
                    <div className="stat-box">
                        <span className="stat-label">Average Coverage</span>
                        <span className={`stat-value ${getCoverageColor(avgCoverage)}`}>{avgCoverage}%</span>
                    </div>
                    <div className="stat-box">
                        <span className="stat-label">Target</span>
                        <span className="stat-value coverage-high">85%</span>
                    </div>
                </div>
            </div>

            {/* LLM Selector */}
            <div className="llm-selector">
                <span><FiCpu /> LLM Provider:</span>
                <select value={llmProvider} onChange={(e) => setLlmProvider(e.target.value)}>
                    <option value="gemini">Gemini 2.0</option>
                    <option value="deepseek">Deepseek</option>
                </select>
            </div>

            {/* Module Grid */}
            <div className="section-header">
                <h2>📊 Select Module to Improve</h2>
            </div>

            <div className="modules-grid">
                {MOCK_MODULES.map((module) => (
                    <div
                        key={module.id}
                        className={`module-card ${selectedModule?.id === module.id ? 'selected' : ''}`}
                        onClick={() => handleModuleClick(module)}
                    >
                        <div className="module-header">
                            <FiFileText className="module-icon" />
                            <div>
                                <h3>{module.name}</h3>
                                <span className="module-path">{module.path}</span>
                            </div>
                        </div>

                        <div className="module-stats">
                            <div className="stat">
                                <span className="stat-value">{module.tests}</span>
                                <span className="stat-label">Tests</span>
                            </div>
                            <div className="stat">
                                <span className={`stat-value ${getCoverageColor(module.coverage)}`}>
                                    {module.coverage}%
                                </span>
                                <span className="stat-label">Coverage</span>
                            </div>
                            <div className="stat">
                                <span className="stat-value">{module.gaps.length}</span>
                                <span className="stat-label">Gaps</span>
                            </div>
                        </div>

                        <div className="coverage-bar">
                            <div
                                className={`coverage-fill ${getCoverageColor(module.coverage)}`}
                                style={{ width: `${module.coverage}%` }}
                            />
                            <div
                                className="coverage-target"
                                style={{ left: `${module.targetCoverage}%` }}
                            />
                        </div>
                    </div>
                ))}
            </div>

            {/* Selected Module Details */}
            {selectedModule && (
                <div className="module-details">
                    <div className="details-header">
                        <div>
                            <h3>📄 {selectedModule.name}</h3>
                            <p className="details-path">{selectedModule.path}</p>
                        </div>
                        <div className="coverage-comparison">
                            <span className={getCoverageColor(selectedModule.coverage)}>
                                {selectedModule.coverage}%
                            </span>
                            <span className="arrow">→</span>
                            <span className="coverage-high">{selectedModule.targetCoverage}%</span>
                        </div>
                    </div>

                    <div className="gaps-section">
                        <h4>⚠️ Coverage Gaps to Fill:</h4>
                        <div className="gaps-grid">
                            {selectedModule.gaps.map((gap, idx) => (
                                <div key={idx} className={`gap-item priority-${gap.priority.toLowerCase()}`}>
                                    <FiAlertCircle className="gap-icon" />
                                    <div>
                                        <span className="gap-name">{gap.name}</span>
                                        <span className="gap-lines">Lines {gap.lines}</span>
                                    </div>
                                    <span className={`priority-badge ${gap.priority.toLowerCase()}`}>
                                        {gap.priority}
                                    </span>
                                </div>
                            ))}
                        </div>
                    </div>

                    <div className="generate-section">
                        <button
                            className="btn btn-primary btn-large generate-btn"
                            onClick={handleGenerate}
                            disabled={isGenerating}
                        >
                            {isGenerating ? (
                                <>
                                    <span className="loading-spinner"></span>
                                    Generating with {llmProvider === 'gemini' ? 'Gemini' : 'Deepseek'}...
                                </>
                            ) : (
                                <>
                                    <FiZap />
                                    Generate Additional Tests
                                </>
                            )}
                        </button>
                        <p className="generate-hint">
                            AI will analyze existing {selectedModule.tests} tests and generate ~{newTestCount} additional test cases
                            to improve coverage from {selectedModule.coverage}% to ~{newCoverage}%
                        </p>
                    </div>
                </div>
            )}

            {/* Results */}
            {generatedTests && (
                <div className="results-section">
                    <div className="results-header">
                        <div>
                            <h2>✅ Generated Additional Tests</h2>
                            <p className="results-meta">
                                {newTestCount} new test cases • Generated in {((generationTime || 3000) / 1000).toFixed(1)}s
                            </p>
                        </div>
                        <div className="coverage-improvement">
                            <span className={getCoverageColor(selectedModule.coverage)}>
                                {selectedModule.coverage}%
                            </span>
                            <span className="arrow">→</span>
                            <span className="coverage-high">{newCoverage}%</span>
                            <span className="improvement-badge">+{newCoverage - selectedModule.coverage}%</span>
                        </div>
                    </div>

                    <div className="code-preview">
                        <pre>{generatedTests}</pre>
                    </div>

                    <div className="results-actions">
                        <button className="btn btn-primary">
                            <FiPlay /> Run All Tests
                        </button>
                        <button className="btn btn-secondary" onClick={handleCopy}>
                            📋 Copy to Clipboard
                        </button>
                        <button className="btn btn-secondary">
                            💾 Merge with {selectedModule.testFile.split('/').pop()}
                        </button>
                    </div>
                </div>
            )}
        </div>
    );
}

export default ImproveTests;
